/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    DetailByteList: typeof import('./components/page/detail/DetailByteList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileHeader: typeof import('./components/page/detail/FileHeader.vue')['default']
    FileTrailer: typeof import('./components/page/detail/FileTrailer.vue')['default']
    FixPageItem: typeof import('./components/FixPageItem.vue')['default']
    GaGa: typeof import('./components/GaGa.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Infimum: typeof import('./components/page/detail/Infimum.vue')['default']
    InnodbPage: typeof import('./components/InnodbPage.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    PageDirectory: typeof import('./components/page/detail/PageDirectory.vue')['default']
    PageHeader: typeof import('./components/page/detail/PageHeader.vue')['default']
    PageOverview: typeof import('./components/PageOverview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlDashboard: typeof import('./components/SqlDashboard.vue')['default']
    Supremum: typeof import('./components/page/detail/Supremum.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
    UserRecord: typeof import('./components/page/detail/UserRecord.vue')['default']
  }
}
