/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    DetailByteItem: typeof import('./components/page/detail/DetailByteItem.vue')['default']
    DetailByteList: typeof import('./components/page/detail/DetailByteList.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileHeader: typeof import('./components/page/detail/FileHeader.vue')['default']
    FileTrailer: typeof import('./components/page/detail/FileTrailer.vue')['default']
    FixPageItem: typeof import('./components/FixPageItem.vue')['default']
    FreeSpace: typeof import('./components/page/detail/FreeSpace.vue')['default']
    Infimum: typeof import('./components/page/detail/Infimum.vue')['default']
    InnodbPage: typeof import('./components/InnodbPage.vue')['default']
    PageDirectory: typeof import('./components/page/detail/PageDirectory.vue')['default']
    PageHeader: typeof import('./components/page/detail/PageHeader.vue')['default']
    RecordHeader: typeof import('./components/page/detail/RecordHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlDashboard: typeof import('./components/SqlDashboard.vue')['default']
    Supremum: typeof import('./components/page/detail/Supremum.vue')['default']
    UserRecord: typeof import('./components/page/detail/UserRecord.vue')['default']
  }
}
